version: "3.7"

services:
  db:
    image: postgres:13
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      - 'POSTGRES_DB:chat'
      - 'POSTGRES_USER:app'
      - 'POSTGRES_PASSWORD:pass'